name:                neutrino-helper
version:             0.1.0.0
github:              "ayachigin/neutrino-helper"
license:             BSD3
author:              "Ayachi Gin"
maintainer:          "ayachigin@gmail.com"
copyright:           "Copyright © 2020 Ayachi Gin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ayachigin/neutrino-helper#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- process
- filepath

library:
  source-dirs: src

executables:
  neutrino-helper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neutrino-helper

tests:
  neutrino-helper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neutrino-helper
